using CppAst;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace VuforiaGen
{
	public sealed class PlatformCompilation
	{
		public PlatformCompilation(string platform, CppCompilation compilation)
		{
			Platform = platform;
			Compilation = compilation;
		}

		public string Platform { get; }

		public CppCompilation Compilation { get; }
	}

	public class CsCodeGenerator
	{
		public static readonly CsCodeGenerator Instance = new CsCodeGenerator();

		private static readonly HashSet<string> UnavailableFunctions = new HashSet<string>
		{
			// Present in the common header, but not exported by the bundled native libraries.
			"vuImageListAppendElement",
		};

		public void Generate(List<PlatformCompilation> platformCompilations, string outputPath)
		{
			// Merge all compilations, deduplicating by name
			var allEnums = new List<CppEnum>();
			var allClasses = new List<CppClass>();
			var allFunctions = new List<CppFunction>();
			var allTypedefs = new List<CppTypedef>();
			var allMacros = new List<CppMacro>();

			var seenEnums = new HashSet<string>();
			var seenClasses = new HashSet<string>();
			var seenFunctions = new HashSet<string>();
			var seenTypedefs = new HashSet<string>();
			var seenMacros = new HashSet<string>();
			var functionPlatforms = new Dictionary<string, HashSet<string>>();

			int anonymousEnumId = 0;
			var seenAnonymousItems = new HashSet<string>();
			foreach (var platformCompilation in platformCompilations)
			{
				var platform = platformCompilation.Platform;
				var compilation = platformCompilation.Compilation;

				foreach (var e in compilation.Enums)
				{
					if (e.IsAnonymous)
					{
						// For anonymous enums, deduplicate by individual item names
						bool hasNewItems = false;
						foreach (var item in e.Items)
						{
							if (!seenAnonymousItems.Contains(item.Name))
								hasNewItems = true;
						}

						if (hasNewItems)
						{
							foreach (var item in e.Items)
								seenAnonymousItems.Add(item.Name);

							var key = $"__anon_{anonymousEnumId++}";
							allEnums.Add(e);
						}
					}
					else
					{
						if (seenEnums.Add(e.Name))
							allEnums.Add(e);
					}
				}

				foreach (var c in compilation.Classes)
				{
					var key = c.Name ?? "";
					if (seenClasses.Add(key))
						allClasses.Add(c);
				}

				foreach (var f in compilation.Functions)
				{
					if (!functionPlatforms.TryGetValue(f.Name, out var platforms))
					{
						platforms = new HashSet<string>();
						functionPlatforms.Add(f.Name, platforms);
					}

					platforms.Add(platform);

					if (seenFunctions.Add(f.Name))
						allFunctions.Add(f);
				}

				foreach (var t in compilation.Typedefs)
				{
					if (seenTypedefs.Add(t.Name))
						allTypedefs.Add(t);
				}

				foreach (var m in compilation.Macros)
				{
					if (seenMacros.Add(m.Name))
						allMacros.Add(m);
				}
			}

			// Pre-collect typedef lists for opaque handle detection
			Helpers.TypedefList = allTypedefs
				.Where(t => Helpers.IsOpaqueType(t))
				.Select(t => t.Name).ToList();

			// Pre-collect delegate type names
			Helpers.DelegateTypes = allTypedefs
				.Where(t => Helpers.IsFunctionPointerTypedef(t))
				.Select(t => t.Name)
				.ToHashSet();

			Console.WriteLine($"Found {allEnums.Count} enums (merged)");
			Console.WriteLine($"Found {allClasses.Count} classes/structs (merged)");
			Console.WriteLine($"Found {allFunctions.Count} functions (merged)");
			Console.WriteLine($"Found {allTypedefs.Count} typedefs (merged)");
			Console.WriteLine($"Found {allMacros.Count} macros (merged)");
			Console.WriteLine($"Found {Helpers.TypedefList.Count} opaque handles");

			// Generate each file
			GenerateConstants(allEnums, allMacros, outputPath);
			GenerateEnums(allEnums, allTypedefs, outputPath);
			GenerateDelegates(allTypedefs, outputPath);
			GenerateStructs(allClasses, outputPath);
			GenerateFunctions(allFunctions, functionPlatforms, outputPath);
			GenerateHandles(allTypedefs, outputPath);
		}

		private void GenerateConstants(List<CppEnum> enums, List<CppMacro> macros, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Constants.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// <auto-generated/>");
			writer.WriteLine("using System;");
			writer.WriteLine();
			writer.WriteLine("namespace Evergine.Bindings.Vuforia");
			writer.WriteLine("{");
			writer.WriteLine("\tpublic static partial class VuforiaNative");
			writer.WriteLine("\t{");

			// VU_CONST_INT values from enums (anonymous enums used as constants)
			var seenConstantNames = new HashSet<string>();
			foreach (var enumDef in enums)
			{
				if (!enumDef.IsAnonymous)
					continue;

				foreach (var item in enumDef.Items)
				{
					// Only include Vuforia constants
					if (!item.Name.StartsWith("VU_"))
						continue;

					// Skip duplicates from multi-platform parsing
					if (!seenConstantNames.Add(item.Name))
						continue;

					Helpers.PrintComments(writer, item.Comment, "\t\t");
					writer.WriteLine($"\t\tpublic const int {item.Name} = {item.Value};");
					writer.WriteLine();
				}
			}

			// Macros as constants
			foreach (var macro in macros)
			{
				if (string.IsNullOrWhiteSpace(macro.Value))
					continue;

				// Only include VU_ prefixed macros
				if (!macro.Name.StartsWith("VU_"))
					continue;

				// Skip function-like macros and internal ones
				if (macro.Name.StartsWith("_") && macro.Name.EndsWith("_"))
					continue;

				// Skip complex macros with operators or function calls
				if (macro.Value.Contains("(") || macro.Value.Contains("|") || macro.Value.Contains("<<"))
					continue;

				// Try to detect type
				if (int.TryParse(macro.Value, out int intVal))
				{
					writer.WriteLine($"\t\tpublic const int {macro.Name} = {macro.Value};");
					writer.WriteLine();
				}
				else if (macro.Value.StartsWith("0x") && int.TryParse(macro.Value.Substring(2), System.Globalization.NumberStyles.HexNumber, null, out _))
				{
					writer.WriteLine($"\t\tpublic const int {macro.Name} = {macro.Value};");
					writer.WriteLine();
				}
			}

			writer.WriteLine("\t}");
			writer.WriteLine("}");

			Console.WriteLine($"Generated: {filePath}");
		}

		private void GenerateEnums(List<CppEnum> enums, List<CppTypedef> typedefs, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Enums.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// <auto-generated/>");
			writer.WriteLine();
			writer.WriteLine("namespace Evergine.Bindings.Vuforia");
			writer.WriteLine("{");

			// Build a set of Flags typedef names
			var flagsTypedefs = typedefs
				.Where(t => t.Name.Contains("Flags"))
				.Select(t => t.Name.Replace("Flags", ""))
				.ToHashSet();

			foreach (var enumDef in enums)
			{
				if (enumDef.Items.Count == 0 || enumDef.IsAnonymous)
					continue;

				// Skip non-Vuforia enums (from system headers)
				if (!string.IsNullOrEmpty(enumDef.Name) && !enumDef.Name.StartsWith("Vu"))
					continue;

				Helpers.PrintComments(writer, enumDef.Comment, "\t");

				// Check if this is a flags enum
				bool isFlags = flagsTypedefs.Contains(enumDef.Name);
				if (isFlags)
				{
					writer.WriteLine("\t[System.Flags]");
				}

				writer.WriteLine($"\tpublic enum {enumDef.Name} : int");
				writer.WriteLine("\t{");

				foreach (var item in enumDef.Items)
				{
					Helpers.PrintComments(writer, item.Comment, "\t\t");
					writer.WriteLine($"\t\t{item.Name} = {item.Value},");
				}

				writer.WriteLine("\t}");
				writer.WriteLine();
			}

			writer.WriteLine("}");

			Console.WriteLine($"Generated: {filePath}");
		}

		private void GenerateDelegates(List<CppTypedef> typedefs, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Delegates.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// <auto-generated/>");
			writer.WriteLine("using System;");
			writer.WriteLine("using System.Runtime.InteropServices;");
			writer.WriteLine();
			writer.WriteLine("namespace Evergine.Bindings.Vuforia");
			writer.WriteLine("{");

			foreach (var typedef in typedefs)
			{
				if (!Helpers.IsFunctionPointerTypedef(typedef))
					continue;

				CppFunctionType funcType = null;
				if (typedef.ElementType is CppPointerType ptrType && ptrType.ElementType is CppFunctionType ft)
				{
					funcType = ft;
				}
				else if (typedef.ElementType is CppFunctionType directFt)
				{
					funcType = directFt;
				}

				if (funcType == null)
					continue;

				Helpers.PrintComments(writer, typedef.Comment, "\t");

				var returnType = Helpers.ConvertToCSharpType(funcType.ReturnType);

				var parameters = new List<string>();
				foreach (var param in funcType.Parameters)
				{
					var paramType = Helpers.ConvertToCSharpType(param.Type);
					var paramName = Helpers.EscapeReservedKeyword(string.IsNullOrEmpty(param.Name) ? $"arg{parameters.Count}" : param.Name);

					// For delegate parameters, use string for const char*
					if (param.Type is CppPointerType paramPtrType && Helpers.IsCharPointer(paramPtrType))
					{
						// For const char* in callbacks, keep as byte* (unsafe)
					}

					parameters.Add($"{paramType} {paramName}");
				}

				writer.WriteLine($"\t[UnmanagedFunctionPointer(CallingConvention.StdCall)]");
				writer.WriteLine($"\tpublic unsafe delegate {returnType} {typedef.Name}({string.Join(", ", parameters)});");
				writer.WriteLine();
			}

			writer.WriteLine("}");

			Console.WriteLine($"Generated: {filePath}");
		}

		private void GenerateStructs(List<CppClass> classes, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Structs.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// <auto-generated/>");
			writer.WriteLine("using System;");
			writer.WriteLine("using System.Runtime.InteropServices;");
			writer.WriteLine("using Evergine.Mathematics;");
			writer.WriteLine();
			writer.WriteLine("namespace Evergine.Bindings.Vuforia");
			writer.WriteLine("{");

			foreach (var classDef in classes)
			{
				if (classDef.ClassKind != CppClassKind.Struct)
					continue;

				if (!classDef.IsDefinition)
					continue;

				// Skip anonymous structs and forward declarations
				if (string.IsNullOrEmpty(classDef.Name))
					continue;

				// Skip opaque type forward declarations (names ending with _)
				if (classDef.Name.EndsWith("_"))
					continue;

				// Skip non-Vuforia structs (from system headers)
				if (!classDef.Name.StartsWith("Vu"))
					continue;

				// Skip structs that are mapped to Evergine.Mathematics types
				if (Helpers.IsMappedType(classDef.Name))
					continue;

				bool isUnion = classDef.ClassKind == CppClassKind.Union;

				Helpers.PrintComments(writer, classDef.Comment, "\t");

				if (isUnion)
				{
					writer.WriteLine("\t[StructLayout(LayoutKind.Explicit)]");
				}
				else
				{
					writer.WriteLine("\t[StructLayout(LayoutKind.Sequential)]");
				}

				writer.WriteLine($"\tpublic unsafe partial struct {classDef.Name}");
				writer.WriteLine("\t{");

				foreach (var field in classDef.Fields)
				{
					if (isUnion)
					{
						writer.WriteLine("\t\t[FieldOffset(0)]");
					}

					Helpers.PrintComments(writer, field.Comment, "\t\t");

					var fieldType = Helpers.ConvertToCSharpType(field.Type);
					var fieldName = Helpers.EscapeReservedKeyword(Helpers.PascalCaseField(field.Name));

					// Handle fixed-size arrays
					if (field.Type is CppArrayType arrayType && arrayType.Size > 0)
					{
						var elementType = Helpers.ConvertToCSharpType(arrayType.ElementType);

						// Fixed-size arrays for primitive types
						if (IsPrimitiveFixedType(elementType))
						{
							writer.WriteLine($"\t\tpublic fixed {elementType} {fieldName}[{arrayType.Size}];");
						}
						else
						{
							// For non-primitive fixed arrays, emit individual fields
							for (int i = 0; i < arrayType.Size; i++)
							{
								writer.WriteLine($"\t\tpublic {elementType} {fieldName}_{i};");
							}
						}
					}
					else if (field.Type is CppPointerType ptrType && Helpers.IsCharPointer(ptrType))
					{
						// const char* fields → byte*
						writer.WriteLine($"\t\tpublic byte* {fieldName};");
					}
					else
					{
						// Check if this is a pointer to a delegate type → IntPtr
						if (field.Type is CppPointerType fieldPtrType
							&& fieldPtrType.ElementType is CppTypedef fieldTd
							&& Helpers.DelegateTypes.Contains(fieldTd.Name))
						{
							writer.WriteLine($"\t\tpublic IntPtr {fieldName};");
						}
						else
						{
							// Regular field
							writer.WriteLine($"\t\tpublic {fieldType} {fieldName};");
						}
					}
				}

				writer.WriteLine("\t}");
				writer.WriteLine();
			}

			writer.WriteLine("}");

			Console.WriteLine($"Generated: {filePath}");
		}

		private void GenerateFunctions(List<CppFunction> functions, Dictionary<string, HashSet<string>> functionPlatforms, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Functions.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// <auto-generated/>");
			writer.WriteLine("using System;");
			writer.WriteLine("using System.Runtime.InteropServices;");
			writer.WriteLine("using Evergine.Mathematics;");
			writer.WriteLine();
			writer.WriteLine("namespace Evergine.Bindings.Vuforia");
			writer.WriteLine("{");
			writer.WriteLine("\tpublic static unsafe partial class VuforiaNative");
			writer.WriteLine("\t{");

			foreach (var function in functions)
			{
				// Skip inline and template functions
				if (function.Flags.HasFlag(CppFunctionFlags.Inline))
					continue;

				if (function.Flags.HasFlag(CppFunctionFlags.FunctionTemplate))
					continue;

				// Skip non-Vuforia functions (system headers leak)
				if (!function.Name.StartsWith("vu"))
					continue;

				if (UnavailableFunctions.Contains(function.Name))
					continue;

				var platformGuard = GetPlatformGuard(functionPlatforms.TryGetValue(function.Name, out var platforms) ? platforms : null);
				if (!string.IsNullOrEmpty(platformGuard))
				{
					writer.WriteLine($"#if {platformGuard}");
				}

				Helpers.PrintComments(writer, function.Comment, "\t\t");

				var returnType = Helpers.ConvertToCSharpType(function.ReturnType);

				// Build parameter list
				var parameters = new List<string>();
				foreach (var param in function.Parameters)
				{
					var paramType = Helpers.ConvertToCSharpType(param.Type);
					var paramName = Helpers.EscapeReservedKeyword(string.IsNullOrEmpty(param.Name) ? $"arg{parameters.Count}" : param.Name);

					// Special handling for const char* parameters → string via marshalling
					if (param.Type is CppPointerType ptrType && Helpers.IsCharPointer(ptrType))
					{
						// Check if it's const char* (input) vs char* (output)
						bool isConst = false;
						if (param.Type is CppPointerType pt)
						{
							if (pt.ElementType is CppQualifiedType qt && qt.Qualifier == CppTypeQualifier.Const)
								isConst = true;
						}

						if (isConst)
						{
							parameters.Add($"[MarshalAs(UnmanagedType.LPStr)] string {paramName}");
							continue;
						}
					}

					// Special handling for const char** parameters → out string or byte**
					if (param.Type is CppPointerType outerPtr
						&& outerPtr.ElementType is CppPointerType innerPtr
						&& Helpers.IsCharPointer(innerPtr))
					{
						parameters.Add($"byte** {paramName}");
						continue;
					}

					// Handle delegate pointer parameters → IntPtr
					if (param.Type is CppPointerType delegatePtr
						&& delegatePtr.ElementType is CppTypedef delegateTd
						&& Helpers.DelegateTypes.Contains(delegateTd.Name))
					{
						parameters.Add($"IntPtr {paramName}");
						continue;
					}

					parameters.Add($"{paramType} {paramName}");
				}

				writer.WriteLine($"\t\t[DllImport(Native.Dll, CallingConvention = Native.Conv)]");
				writer.WriteLine($"\t\tpublic static extern {returnType} {function.Name}({string.Join(", ", parameters)});");

				if (!string.IsNullOrEmpty(platformGuard))
				{
					writer.WriteLine("#endif");
				}

				writer.WriteLine();
			}

			writer.WriteLine("\t}");
			writer.WriteLine("}");

			Console.WriteLine($"Generated: {filePath}");
		}

		// A function the header exposes on one platform only must be declared on that
		// platform only. Both directions matter, and only one of them was covered: the
		// Android-only functions were guarded with !__IOS__ while the iOS-only ones fell
		// through to null and were declared unconditionally. That put four ARKit imports --
		// vuPlatformiOSConfigDefault, vuPlatformControllerGetARKitInfo,
		// vuPlatformControllerSetARKitConfig and vuEngineConfigSetAddPlatformiOSConfig --
		// into the net10.0 target, which is the one that runs on Android, where
		// libVuforiaEngine.so does not export them. They compile and would throw
		// EntryPointNotFoundException on the first call.
		//
		// Expressed as !__IOS__ / __IOS__ rather than __ANDROID__ / __IOS__ because the
		// package targets net10.0 and net10.0-ios: __IOS__ is defined for the second, and
		// the first is where Android lives.
		private static string GetPlatformGuard(HashSet<string> platforms)
		{
			if (platforms == null || platforms.Count != 1)
				return null;

			if (platforms.Contains("Android"))
				return "!__IOS__";

			if (platforms.Contains("iOS"))
				return "__IOS__";

			return null;
		}

		private void GenerateHandles(List<CppTypedef> typedefs, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Handles.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// <auto-generated/>");
			writer.WriteLine("using System;");
			writer.WriteLine();
			writer.WriteLine("namespace Evergine.Bindings.Vuforia");
			writer.WriteLine("{");

			foreach (var typedef in typedefs)
			{
				if (!Helpers.IsOpaqueType(typedef))
					continue;

				var name = typedef.Name;

				Helpers.PrintComments(writer, typedef.Comment, "\t");
				writer.WriteLine($"\tpublic partial struct {name} : IEquatable<{name}>");
				writer.WriteLine("\t{");
				writer.WriteLine($"\t\tpublic readonly IntPtr Handle;");
				writer.WriteLine();
				writer.WriteLine($"\t\tpublic {name}(IntPtr existingHandle) {{ Handle = existingHandle; }}");
				writer.WriteLine();
				writer.WriteLine($"\t\tpublic static {name} Null => new {name}(IntPtr.Zero);");
				writer.WriteLine();
				writer.WriteLine($"\t\tpublic static implicit operator {name}(IntPtr handle) => new {name}(handle);");
				writer.WriteLine();
				writer.WriteLine($"\t\tpublic static bool operator ==({name} left, {name} right) => left.Handle == right.Handle;");
				writer.WriteLine();
				writer.WriteLine($"\t\tpublic static bool operator !=({name} left, {name} right) => left.Handle != right.Handle;");
				writer.WriteLine();
				writer.WriteLine($"\t\tpublic bool Equals({name} h) => Handle == h.Handle;");
				writer.WriteLine();
				writer.WriteLine($"\t\tpublic override bool Equals(object o) => o is {name} h && Equals(h);");
				writer.WriteLine();
				writer.WriteLine($"\t\tpublic override int GetHashCode() => Handle.GetHashCode();");
				writer.WriteLine("\t}");
				writer.WriteLine();
			}

			writer.WriteLine("}");

			Console.WriteLine($"Generated: {filePath}");
		}

		private static bool IsPrimitiveFixedType(string typeName)
		{
			return typeName switch
			{
				"bool" or "byte" or "sbyte" or "short" or "ushort" or
				"int" or "uint" or "long" or "ulong" or "float" or "double" or "char" => true,
				_ => false,
			};
		}
	}
}
